apiVersion: v1
kind: List
items:
  - kind: ImageStream
    apiVersion: "v1"
    metadata:
      annotations:
        description: Sample app
        tags: java
      labels:
        app: spring-boot
      name: spring-boot

  - kind: BuildConfig
    apiVersion: "v1"
    metadata:
      labels:
        app: spring-boot
      name: spring-boot
    spec:
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 1
      runPolicy: "Serial"

      triggers:
        - github:
            secret: ccp
          type: GitHub
        - generic:
            secret: ccp
          type: Generic
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange

      source:
        git:
          uri: https://github.com/redhat-capgemini-exchange/spring-boot-http-booster
          ref: "main"
        type: Git

      strategy:
        sourceStrategy:
          env:
            - name: EXTRA_MAVEN_OPTS
              value: ""
          
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: "java:openjdk-11-ubi8"

        type: Source

      output:
        to:
          kind: ImageStreamTag
          name: 'spring-boot:1.0.0'
