apiVersion: v1
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: Defines how to deploy the application
        template.alpha.openshift.io/wait-for-ready: "true"
      name: spring-boot
      labels:
        app: spring-boot
    spec:
      replicas: 1
      selector:
        name: spring-boot
      strategy:
        type: Recreate
        recreateParams:
          #pre:
          #  execNewPod:
          #    command:
          #      - migrate-database
          #    containerName: spring-boot
          #  failurePolicy: Ignore

      template:
        metadata:
          name: spring-boot
          labels:
            name: spring-boot
            app: spring-boot
        spec:
          containers:
            - env:
                - name: KEYBASE
                  valueFrom:
                    secretKeyRef:
                      key: keybase
                      name: spring-boot-secrets

              image: ""
              name: spring-boot
              ports:
                - containerPort: 8080

              #livenessProbe:
              #  httpGet:
              #    path: /status/alive
              #    port: 8080
              #  initialDelaySeconds: 60
              #  timeoutSeconds: 3

              #readinessProbe:
              #  httpGet:
              #    path: /status/ready
              #    port: 8080
              #  initialDelaySeconds: 30
              #  timeoutSeconds: 5

              resources:
                limits:
                  memory: "512Mi"

      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - spring-boot
            from:
              kind: ImageStreamTag
              name: "spring-boot:1.0.0"
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Exposes and load balances the application pods
      name: spring-boot
      labels:
        app: spring-boot
    spec:
      ports:
        - name: spring-boot
          port: 8080
          targetPort: 8080
      selector:
        name: spring-boot

  - apiVersion: v1
    kind: Route
    metadata:
      name: spring-boot
      labels:
        app: spring-boot
    spec:
      to:
        kind: Service
        name: spring-boot

kind: List
